DROP DATABASE IF EXISTS LOJA_DE_MOTOS;
CREATE DATABASE LOJA_DE_MOTOS;
USE LOJA_DE_MOTOS;


CREATE TABLE CLIENTES (
    CPF VARCHAR(16),
    NOME VARCHAR(50) NOT NULL,
    RENDA_MENSAL FLOAT NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(16) NOT NULL,
    PRIMARY KEY(CPF)
);


CREATE TABLE CONSULTORES (
    MATRICULA VARCHAR(10),
    NOME VARCHAR(50) NOT NULL,
    SALARIO FLOAT NOT NULL,
    COMISSAO FLOAT,
    PRIMARY KEY(MATRICULA)
);


CREATE TABLE FORMA_PAG(
    ID INT,
    TIPO VARCHAR(20) NOT NULL,
    PRIMARY KEY(ID)
);


CREATE TABLE VENDAS (
    CODIGO INT,
    DATA_ DATE NOT NULL,
    VALOR FLOAT NOT NULL,
    CPF VARCHAR(16) NOT NULL,
    MATRICULA VARCHAR(10) NOT NULL,
    PRIMARY KEY(CODIGO),
    FOREIGN KEY(CPF) REFERENCES CLIENTES(CPF),
    FOREIGN KEY(MATRICULA) REFERENCES CONSULTORES(MATRICULA)
);


CREATE TABLE FORMA_PAG_VENDAS (
    ID INT,
    CODIGO INT,
    PRIMARY KEY(ID, CODIGO),
    FOREIGN KEY(ID) REFERENCES FORMA_PAG(ID),
    FOREIGN KEY(CODIGO) REFERENCES VENDAS(CODIGO)
);


CREATE TABLE REPRESENTANTES (
    ID INT,
    NOME VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(16) NOT NULL,
    PRIMARY KEY(ID)
);


CREATE TABLE MONTADORAS (
    CODIGO INT,
    NOME VARCHAR(30) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    TELEFONE VARCHAR(16),
    ID INT,
    PRIMARY KEY(CODIGO),
    FOREIGN KEY(ID) REFERENCES REPRESENTANTES(ID)
);


CREATE TABLE MOTOS (
    CODIGO VARCHAR(10),
    MODELO VARCHAR(10) NOT NULL,
    ANO_FABRI DATE NOT NULL,
    ANO_MODELO DATE NOT NULL,
    PRECO_VISTA FLOAT NOT NULL,
    PRIMARY KEY(CODIGO)
);


CREATE TABLE VENDAS_MOTOS (
    CODIGO_VENDAS INT,
    CODIGO_MOTOS VARCHAR(10),
    PRIMARY KEY (CODIGO_VENDAS, CODIGO_MOTOS),
    FOREIGN KEY(CODIGO_VENDAS) REFERENCES VENDAS(CODIGO),
    FOREIGN KEY(CODIGO_MOTOS) REFERENCES MOTOS(CODIGO)
);


DESCRIBE CLIENTES;
DESCRIBE CONSULTORES;
DESCRIBE FORMA_PAG;
DESCRIBE VENDAS;
DESCRIBE FORMA_PAG_VENDAS;
DESCRIBE REPRESENTANTES;
DESCRIBE MONTADORAS;
DESCRIBE MOTOS;
DESCRIBE VENDAS_MOTOS;
